/*
Name:       Soren Bradley, Joe Spurway
Email:      sbrad910@mtroyal.ca
Course:     COMP 2659-001
Semester:   Winter 2022
Instructor: Paul Pospisil

Project: Puals Astro Golf Adventure (Paga)

File: BITMAPS.H

*/
#ifndef BITMAPS_H
#define BITMAPS_H

#include "types.h"

/**extern const UINT32 ball_arrows[NNN_arrow, NNE_arrow, NEE_arrow, EEE_arrow, SNE_arrow, SSE_arrow, 
                            SSS_arrow, SSW_arrow, SWW_arrow, WWW_arrow, WSW_arrow, WNN_arrow]; 
**/

extern const UINT16 NNN_arrow [];
extern const UINT16 NNE_arrow [];
extern const UINT16 NEE_arrow [];
extern const UINT16 EEE_arrow [];
extern const UINT16 SNE_arrow [];
extern const UINT16 SSE_arrow [];
extern const UINT16 SSS_arrow [];
extern const UINT16 SSW_arrow [];
extern const UINT16 SWW_arrow [];
extern const UINT16 WWW_arrow [];
extern const UINT16 WSW_arrow [];
extern const UINT16 WNN_arrow [];
extern const UINT8 ball_small [];
extern const UINT16 ball [];
extern const UINT16 portal_inactive [];
extern const UINT16 portal_active [];
extern const UINT16 hole_bitmap [];
extern const UINT16 wall_tile [];
extern const UINT16 ground_tile [];
extern const UINT16 power_indicator_on [];
extern const UINT16 power_indicator_off [];
extern const UINT8 power_text [][];
extern const UINT8 player_text [][];
extern const UINT8 score_text [][];
extern const UINT8 map_number_text [][];
extern const UINT8 par_text [][];
extern const UINT8 shots_text [][];
extern const UINT8 number_text [][];
extern const UINT8 ball_hit [][];
extern const UINT8 no_ball_hit [][];
extern const UINT8 mouse_ball [];




#endif